// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi7Wscnn6oSGZT7Dw_3fOJ8q2FSkpz-sc',
    appId: '1:703873230238:web:71e250327e0e038308628f',
    messagingSenderId: '703873230238',
    projectId: 'sim-perumahan-3d9f3',
    authDomain: 'sim-perumahan-3d9f3.firebaseapp.com',
    storageBucket: 'sim-perumahan-3d9f3.firebasestorage.app',
    measurementId: 'G-EN0VFZEZNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4MXtq5Wl88LzSiQLMvs7kal_xZAI1vaM',
    appId: '1:703873230238:android:88f8117a6aadf13208628f',
    messagingSenderId: '703873230238',
    projectId: 'sim-perumahan-3d9f3',
    storageBucket: 'sim-perumahan-3d9f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL6bHv6YX-oSAPIRGEZpWfQ9V4MjY80bE',
    appId: '1:703873230238:ios:3357c81ed5b9f3f008628f',
    messagingSenderId: '703873230238',
    projectId: 'sim-perumahan-3d9f3',
    storageBucket: 'sim-perumahan-3d9f3.firebasestorage.app',
    iosBundleId: 'com.sim.perumahan.simPerumahan2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL6bHv6YX-oSAPIRGEZpWfQ9V4MjY80bE',
    appId: '1:703873230238:ios:3357c81ed5b9f3f008628f',
    messagingSenderId: '703873230238',
    projectId: 'sim-perumahan-3d9f3',
    storageBucket: 'sim-perumahan-3d9f3.firebasestorage.app',
    iosBundleId: 'com.sim.perumahan.simPerumahan2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBi7Wscnn6oSGZT7Dw_3fOJ8q2FSkpz-sc',
    appId: '1:703873230238:web:80f323b78b93af8208628f',
    messagingSenderId: '703873230238',
    projectId: 'sim-perumahan-3d9f3',
    authDomain: 'sim-perumahan-3d9f3.firebaseapp.com',
    storageBucket: 'sim-perumahan-3d9f3.firebasestorage.app',
    measurementId: 'G-G99C40MR4Y',
  );
}
